### ISSUE TITLE
Wishlist: backend without a port driver

### ISSUE THREAD

**Issue by davidw** [basho/lager_syslog#11]
https://github.com/Vagabond/erlang-syslog/issues/9

I don't understand the details of the C code involved in this issue, as I haven't had a close look, but it'd be nice to have a pure Erlang backend in any event, something that can talk to syslogd directly.

**Comment by Vagabond** [comment]
There used to be a syslog backend that used the syslog UDP protocol, rather than than syslog(3) C interface (which is why we need C code here).

**Comment by Vagabond** [comment]
https://github.com/abs/lager_syslogerl

**Comment by mrallen1** [comment]
Cool. Didn't know about that. Thank you. :+1:
