### ISSUE TITLE
Please add a License

### ISSUE THREAD

**Issue by sebastian** [basho/lager_syslog#19]
Would you please be so kind as to add a license to this repository, so it is clear how it is licensed out?

I am assuming you are intending Apache V2, since that seems to be what you use, and also what is written in the header of `lager_syslog_backend.erl`, but if you could explicitly add a license, it would help greatly!

Thank you!

**Comment by mrallen1** [comment]
Added in 62f3a41. Should be merged pretty soon.

**Comment by sebastian** [comment]
That's fantastic. Thank you very much!
