### ISSUE TITLE
lager_syslog on hex.pm

### ISSUE THREAD

**Issue by lucafavatella** [basho/lager_syslog#29]
It appears not to be [there](https://hex.pm/packages?search=syslog&sort=downloads)

See also https://github.com/erlang-lager/lager/issues/400

**Comment by lucafavatella** [comment]
Moving syslog dependency to hex.pm may be a dependency of this.

**Comment by lucafavatella** [comment]
I understand rebar3/hex do not support packages with native code, and I understand a hex package "requirement" [must](http://www.rebar3.org/docs/publishing-packages) be a hex package as well. Hence closing this ticket.

**Comment by MonsieurV** [comment]
Hi there,

Seems like all this package requirements are now on Hex, including [erlang-syslog](https://hex.pm/packages/syslog).

Could it be added on Hex then? @basho
